channels:
  - anaconda
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - antlr-python-runtime=4.9.3
  - appdirs=1.4.4
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - click=8.1.7
  - comm=0.2.2
  - cuda-cudart=12.4.127
  - cuda-cudart_linux-64=12.4.127
  - cuda-cupti=12.4.127
  - cuda-libraries=12.4.1
  - cuda-nvrtc=12.4.127
  - cuda-nvtx=12.4.127
  - cuda-opencl=12.4.127
  - cuda-runtime=12.4.1
  - cuda-version=12.4
  - debugpy=1.6.7
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - executing=2.1.0
  - fastcache=1.1.0
  - ffmpeg=4.2.2
  - filelock=3.13.1
  - freetype=2.12.1
  - fsspec=2024.6.1
  - giflib=5.2.2
  - gitdb=4.0.7
  - gitpython=3.1.43
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - huggingface_hub=0.24.6
  - hydra=2.5
  - hydra-core=1.3.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - importlib_resources=6.4.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - jinja2=3.1.4
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - lerc=3.0
  - libabseil=20240116.2
  - libcublas=12.4.5.8
  - libcufft=11.2.1.3
  - libcufile=1.9.1.3
  - libcurand=10.3.5.147
  - libcusolver=11.6.1.9
  - libcusparse=12.3.1.170
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=14.2.0
  - libidn2=2.3.4
  - libjpeg-turbo=2.0.0
  - libnpp=12.2.5.30
  - libnvfatbin=12.4.127
  - libnvjitlink=12.4.127
  - libnvjpeg=12.3.1.117
  - libopus=1.3.1
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsodium=1.0.20
  - libstdcxx=14.2.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - lightning=2.3.3
  - lightning-utilities=0.11.8
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - markupsafe=2.1.3
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpmath=1.3.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - networkx=3.1
  - numpy=1.24.3
  - numpy-base=1.24.3
  - ocl-icd=2.3.2
  - omegaconf=2.3.0
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.1
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - platformdirs=3.10.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.48
  - prompt_toolkit=3.0.48
  - protobuf=4.25.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.18.0
  - pysocks=1.7.1
  - python=3.8.20
  - python_abi=3.8
  - pytorch=2.4.1
  - pytorch-cuda=12.4
  - pytorch-lightning=2.4.0
  - pytorch-mutex=1.0
  - pyyaml=6.0.2
  - pyzmq=25.1.2
  - readline=8.2
  - requests=2.32.3
  - safetensors=0.4.5
  - scikit-learn=1.3.0
  - sentry-sdk=1.9.0
  - setproctitle=1.2.2
  - setuptools=75.1.0
  - six=1.16.0
  - smmap=4.0.0
  - sqlite=3.45.3
  - stack_data=0.6.2
  - sympy=1.5.1
  - tbb=2021.8.0
  - threadpoolctl=3.5.0
  - timm=1.0.11
  - tk=8.6.14
  - torchmetrics=1.4.0.post0
  - torchtriton=3.0.0
  - torchvision=0.20.0
  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - urllib3=2.2.3
  - wandb=0.16.6
  - wcwidth=0.2.13
  - wheel=0.44.0
  - x264=1!157.20191217
  - xz=5.4.6
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - babel==2.16.0
      - cffi==1.17.1
      - chardet==5.2.0
      - contourpy==1.1.1
      - cryptography==45.0.2
      - cycler==0.12.1
      - fonttools==4.54.1
      - google-measurement-protocol==1.1.0
      - huggingface-hub==0.26.2
      - inquirerpy==0.3.4
      - jeepney==0.9.0
      - kiwisolver==1.4.7
      - matplotlib==3.7.5
      - mutagen==1.47.0
      - pfzy==0.3.4
      - prices==1.1.1
      - pycocoevalcap==1.2
      - pycocotools==2.0.7
      - pycparser==2.22
      - pycryptodomex==3.23.0
      - pyparsing==3.1.4
      - pysrt==1.1.2
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - scikit-video==1.1.11
      - scipy==1.10.1
      - secretstorage==3.3.3
      - soccernet==0.1.61
      - websockets==13.1
      - yt-dlp==2024.10.22