defaults:
  - /datasets/@train.dataset: summary
  - /datasets/@valid.dataset: summary
  - /datasets/@test.dataset: summary
  - _self_

_target_: datamodules.datamodule.DataModule
_recursive_: True
splits:
  - train
  - valid
  - test
train:
  dataset:
    split: train
  batch_size: ${batch_size}
  shuffle: True
  num_workers: ${num_workers}
  pin_memory: True
  drop_last: False
valid:
  dataset:
    split: valid
  batch_size: ${batch_size}
  shuffle: False
  num_workers: ${num_workers}
  pin_memory: True
  drop_last: False
test:
  dataset:
    split: test
  batch_size: ${batch_size}
  shuffle: False
  num_workers: ${num_workers}
  pin_memory: True
  drop_last: False