defaults:
  - /datamodules@datamodule: default
  - /models@model: default
  - /trainer@trainer: default
  - _self_

data_dir: data
batch_size: 1
window_size_sec: 60
frame_rate: 2
num_workers: 5
splits:
  - predict
include_actions: False
include_cameras: False

return_predictions: True
save_output: True

output_path: output.json
checkpoint: weights/Baseline_VideoMAEv2-Giant.ckpt

model:
  input_dim: 1408
  ndim: 256
  head:
    _target_: models.heads.DSNetAFHead
    ndim: ${..ndim}
    nheads: 2
    num_classes: 1
    weights: [1.0, 0.05]

datamodule:
  splits: ${splits}
  train: null
  valid: null
  test: null
  predict: 
    dataset:
      game_list: ${data_dir}/test.txt
      filename: intervals.srt
      frames_dir: 'HQ_224p'
      regression: True
      preload_features:
        name: videoMAEv2-giant
        filename: HQ_224p_VideoMAEv2_Giant_K710_1408.npy
        ndim: ${model.input_dim}
    shuffle: False

trainer:
  logger: null
  callbacks: null
  enable_checkpointing: False
  benchmark: True

seed:
  _target_: lightning.fabric.utilities.seed.seed_everything
  seed: 42
  workers: True

hydra:
  hydra_logging:
    level: INFO
    format: '{time:%Y-%m-%d %H:%M:%S} - {name} - {level: <8} - {message}'