defaults:
  - /datamodules@datamodule: default
  - /models@model: defaults
  - /trainer@trainer: default
  - _self_

data_dir: data
batch_size: 64
window_size_sec: 60
frame_rate: 2
num_workers: 5
splits:
  - train
  - valid
include_actions: False
include_cameras: False

model:
  input_dim: 384
  ndim: 256
  head:
    _target_: models.heads.DSNetAFHead
    ndim: ${..ndim}
    nheads: 2
    num_classes: 1
    weights: [1.0, 0.05]
  loss_fn: 
  -   _target_: torch.nn.BCEWithLogitsLoss
      _recursive_: True
      weight:
        _target_: torch.tensor
        data: 1.0
      reduction: mean
  -   _target_: torch.nn.SmoothL1Loss
      reduction: mean
  weights: null

datamodule:
  splits: ${splits}
  train:
    dataset:
      game_list: ${data_dir}/train.txt
      filename: intervals.srt
      frames_dir: 'HQ_224p'
      regression: True
      preload_features:
        name: videoMAEv2-small
        filename: HQ_224p_VideoMAEv2_SmallFromGiant_K710_384.npy
        ndim: ${model.input_dim}
    shuffle: True
  valid: 
    dataset:
      game_list: ${data_dir}/validation.txt
      filename: ${datamodule.train.dataset.filename}
      frames_dir: 'HQ_224p'
      stride: 0
      regression: True
      preload_features:
        name: ${datamodule.train.dataset.preload_features.name}
        filename: ${datamodule.train.dataset.preload_features.filename}
        ndim: ${model.input_dim}
    shuffle: False
  test: null
  predict: null

trainer:
  logger: null
  callbacks: null
  enable_checkpointing: False
  benchmark: True

seed:
  _target_: lightning.fabric.utilities.seed.seed_everything
  seed: 42
  workers: True

hydra:
  hydra_logging:
    level: INFO
    format: '{time:%Y-%m-%d %H:%M:%S} - {name} - {level: <8} - {message}'